import { normalizeCode } from "@/shared/lib";

interface IdentityAccessBadgeToken {
  border: string;
  background: string;
  text: string;
}

const IDENTITY_ACCESS_BADGE_TOKENS: readonly IdentityAccessBadgeToken[] = [
  { border: "border-primary/40", background: "bg-primary/15", text: "text-primary" },
  { border: "border-success/40", background: "bg-success/15", text: "text-success" },
  { border: "border-warning/40", background: "bg-warning/20", text: "text-warning" },
  { border: "border-destructive/30", background: "bg-destructive/15", text: "text-destructive" },
  {
    border: "border-secondary/70",
    background: "bg-secondary/60",
    text: "text-secondary-foreground",
  },
  { border: "border-accent", background: "bg-accent/15", text: "text-accent-foreground" },
  { border: "border-sky-400/40", background: "bg-sky-400/15", text: "text-sky-300" },
  { border: "border-fuchsia-400/40", background: "bg-fuchsia-400/15", text: "text-fuchsia-300" },
  { border: "border-emerald-400/40", background: "bg-emerald-400/15", text: "text-emerald-300" },
  { border: "border-rose-400/40", background: "bg-rose-400/15", text: "text-rose-300" },
  { border: "border-amber-400/40", background: "bg-amber-400/15", text: "text-amber-300" },
  { border: "border-violet-400/40", background: "bg-violet-400/15", text: "text-violet-300" },
] as const;

function createBadgeClass(token: IdentityAccessBadgeToken): string {
  return `${token.border} ${token.background} ${token.text}`;
}

function createBadgePalette(tokens: readonly IdentityAccessBadgeToken[]): string[] {
  return tokens.map((token) => createBadgeClass(token));
}

const IDENTITY_ACCESS_BADGE_PALETTE = createBadgePalette(IDENTITY_ACCESS_BADGE_TOKENS);

function hashString(input: string): number {
  let hash = 0;
  for (let index = 0; index < input.length; index += 1) {
    hash = (hash << 5) - hash + input.charCodeAt(index);
    hash |= 0;
  }
  return Math.abs(hash);
}

/**
 * Generates a deterministic class map for identity access badge colors.
 *
 * @param codes - List of identity access codes.
 * @returns Map where key is normalized access code and value is Tailwind class string.
 */
export function getIdentityAccessBadgeClassMap(codes: string[]): Record<string, string> {
  const uniqueCodes = Array.from(
    new Set(codes.map((code) => normalizeCode(code)).filter((code) => code !== ""))
  );

  const usedSlots = new Set<number>();
  const result: Record<string, string> = {};

  for (const code of uniqueCodes) {
    let slot = hashString(code) % IDENTITY_ACCESS_BADGE_PALETTE.length;
    let safetyCounter = 0;

    while (usedSlots.has(slot) && safetyCounter < IDENTITY_ACCESS_BADGE_PALETTE.length) {
      slot = (slot + 1) % IDENTITY_ACCESS_BADGE_PALETTE.length;
      safetyCounter += 1;
    }

    usedSlots.add(slot);
    result[code] = IDENTITY_ACCESS_BADGE_PALETTE[slot];
  }

  return result;
}

/**
 * Reads the visual class for a single identity access badge.
 *
 * @param badgeClassMap - Class map generated by {@link getIdentityAccessBadgeClassMap}.
 * @param code - Raw identity access code.
 * @returns Tailwind class string for badge styling.
 */
export function getIdentityAccessBadgeClass(
  badgeClassMap: Record<string, string>,
  code: string
): string {
  const normalizedCode = normalizeCode(code);
  return badgeClassMap[normalizedCode] ?? createBadgeClass(IDENTITY_ACCESS_BADGE_TOKENS[5]);
}
